skinparam activity {
  BackgroundColor lightblue
  BorderColor #33668E
  FontColor black
  FontName arial
}

skinparam diamond {
  BackgroundColor #ccf
  LineColor #00FF00
  FontColor green
  FontName arial
  FontSize 15
}

skinparam arrow {
  FontColor green
  FontName arial
  FontSize 15
}

skinparam partition {
  LineColor red
  FontColor green
  RoundCorner 10
  BackgroundColor PeachPuff
}

skinparam note {
  FontColor Blue
  LineColor Navy
  BackgroundColor #ccf
}

skinparam document {
  BackgroundColor white
}
